include .env
.PHONY: up mgmt crud churn env down open ingest
up:    ; ./dev up
mgmt:  ; ./dev mgmt
crud:  ; ./dev crud
churn: ; ./dev churn $(ARGS)
env:   ; ./dev env
down:  ; ./dev down
open:  ; ./dev open
ingest: ; ./dev ingest $(ARGS)
