name: Auto PR on push

on:
  push:
    branches-ignore:
      - main
      - 'release/**'
      - 'hotfix/**'

jobs:
  open-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Create or update PR
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const branch = context.ref.replace('refs/heads/', '');
            const { owner, repo } = context.repo;
            const base = 'main';
            const title = `auto: PR for ${branch}`;
            const body = `Auto-created PR for branch ${branch}. Please review and squash-merge.`;

            const existing = await github.paginate(github.rest.pulls.list, {
              owner,
              repo,
              state: 'open',
              head: `${owner}:${branch}`,
              base
            });

            if (existing.length > 0) {
              core.info(`PR exists: ${existing[0].html_url}`);
              core.setOutput('number', existing[0].number);
              core.setOutput('url', existing[0].html_url);
            } else {
              const pr = await github.rest.pulls.create({ owner, repo, head: branch, base, title, body });
              core.info(`Created PR: ${pr.data.html_url}`);
              core.setOutput('number', pr.data.number);
              core.setOutput('url', pr.data.html_url);
              try {
                await github.rest.pulls.requestReviewers({ owner, repo, pull_number: pr.data.number, reviewers: ['KDReiners'] });
              } catch (e) {
                core.warning(`Request reviewers failed: ${e.message}`);
              }
            }

